// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOsKrJ5nNvPAc5Jq1fvrMtg6WGqE6gWc',
    appId: '1:1096480624317:web:2fa7ccbf3b224a05cdb1d4',
    messagingSenderId: '1096480624317',
    projectId: 'musafer-bus-transport',
    authDomain: 'musafer-bus-transport.firebaseapp.com',
    storageBucket: 'musafer-bus-transport.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjiPrSnk9vTJxQ_2V7lv7mt7jZ_ib-LVs',
    appId: '1:1096480624317:android:da4fa5f68a8273efcdb1d4',
    messagingSenderId: '1096480624317',
    projectId: 'musafer-bus-transport',
    storageBucket: 'musafer-bus-transport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OgaIhAiT6Wb9llU2ujjO-sgui20Jhw8',
    appId: '1:1096480624317:ios:f5932bdb988b1987cdb1d4',
    messagingSenderId: '1096480624317',
    projectId: 'musafer-bus-transport',
    storageBucket: 'musafer-bus-transport.firebasestorage.app',
    androidClientId: '1096480624317-hvdlim3tlcr7a07h4a5jmemrknfr5d2i.apps.googleusercontent.com',
    iosClientId: '1096480624317-6rrd4at4u81tqaetq05dlrmgm51kvlk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverBusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8OgaIhAiT6Wb9llU2ujjO-sgui20Jhw8',
    appId: '1:1096480624317:ios:f5932bdb988b1987cdb1d4',
    messagingSenderId: '1096480624317',
    projectId: 'musafer-bus-transport',
    storageBucket: 'musafer-bus-transport.firebasestorage.app',
    androidClientId: '1096480624317-hvdlim3tlcr7a07h4a5jmemrknfr5d2i.apps.googleusercontent.com',
    iosClientId: '1096480624317-6rrd4at4u81tqaetq05dlrmgm51kvlk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverBusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmOsKrJ5nNvPAc5Jq1fvrMtg6WGqE6gWc',
    appId: '1:1096480624317:web:81ba38f8eb5a4f4acdb1d4',
    messagingSenderId: '1096480624317',
    projectId: 'musafer-bus-transport',
    authDomain: 'musafer-bus-transport.firebaseapp.com',
    storageBucket: 'musafer-bus-transport.firebasestorage.app',
  );
}
