// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7nfJWv1p69m6ktOtJ_mS65dqVOsN7Os',
    appId: '1:900435508634:web:42737403e880a48da90e23',
    messagingSenderId: '900435508634',
    projectId: 'driver-bus-app',
    authDomain: 'driver-bus-app.firebaseapp.com',
    storageBucket: 'driver-bus-app.firebasestorage.app',
    measurementId: 'G-JGNW8NHWL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJ2dUTrIUqvpLgVuO-4bwoU_srA25fmQ',
    appId: '1:900435508634:android:5e07973d7fd94944a90e23',
    messagingSenderId: '900435508634',
    projectId: 'driver-bus-app',
    storageBucket: 'driver-bus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmsjJqrXakCr0xWGy6X96gOUTVfBLKMUA',
    appId: '1:900435508634:ios:9d8e19a894ec0679a90e23',
    messagingSenderId: '900435508634',
    projectId: 'driver-bus-app',
    storageBucket: 'driver-bus-app.firebasestorage.app',
    iosBundleId: 'com.example.driverBusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmsjJqrXakCr0xWGy6X96gOUTVfBLKMUA',
    appId: '1:900435508634:ios:9d8e19a894ec0679a90e23',
    messagingSenderId: '900435508634',
    projectId: 'driver-bus-app',
    storageBucket: 'driver-bus-app.firebasestorage.app',
    iosBundleId: 'com.example.driverBusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7nfJWv1p69m6ktOtJ_mS65dqVOsN7Os',
    appId: '1:900435508634:web:2b933cf99e0a04bea90e23',
    messagingSenderId: '900435508634',
    projectId: 'driver-bus-app',
    authDomain: 'driver-bus-app.firebaseapp.com',
    storageBucket: 'driver-bus-app.firebasestorage.app',
    measurementId: 'G-EH204F6LB0',
  );

}